add some instructions on data transfer RAP-VM
activityMonitoring/wearable-teaching pull request #24
Opened 2022-12-06 12:47 UTC by R-Walmsley

2022-12-06 12:49 UTC, R-Walmsley commented
@gmertes I have roughly tested these. We can then point the students to them.

2022-12-06 18:24 UTC, gmertes requested changes
Thanks Rosemary, this looks great! I would just swap out venv for their conda environments, since they'll have that active most, if not all, of the time anyway. Then the dx tool is always easily available.

2022-12-06 18:24 UTC, gmertes commented on _posts/2022-11-30-prac5-6-Association-Analysis-in-UK-Biobank.md
> +```
I would change this to their existing anaconda environments, I tested it with the template environment and there don't seem to be dependency conflicts. So you could change the install instructions to just pip install in their conda environment:

```
conda activate wearables_workshop
pip3 install dxpy
```

2022-12-07 08:07 UTC, R-Walmsley commented on _posts/2022-11-30-prac5-6-Association-Analysis-in-UK-Biobank.md
> +```
Thanks, change made. Good spot as I had no idea they had these set up!

2022-12-07 12:04 UTC, gmertes approved these changes

2022-12-07 12:05 UTC, merged